# Feature flags
email_enabled: true
generate_transcript: true
filter_since_last_schedule: true
use_tts: true
include_keyword_papers: false

# LLM Call Configurations
influence_filter:
  provider: openai
  model: gpt-5-mini-2025-08-07

ranking:
  provider: openai
  model: gpt-5-2025-08-07

podcast:
  provider: gemini
  model: gemini-3-pro-preview

tts:
  provider: gemini
  model: gemini-2.5-flash-preview-tts
  voice: Zephyr

affiliation:
  provider: gemini
  model: gemini-3-flash-preview

# Other settings
compress_to_64kbps: true
pricing_path: my_config/pricing.json
ir_limit: 50
nlp_limit: 50
others_limit: 50
keywords_path: my_config/keywords.yaml
top_n: 3
top_n_tts: 3
abst_word_cutoff: 200
transcript_word_cutoff: 1000
arxiv_timeout: 30
openai_timeout: 180
influence_score_threshold: 3
